'use client'
import * as React from 'react'
import { Button } from '@/components/ui/button'
import { Dialog } from '@/components/ui/dialog'
import { Field, Input, Select } from '@/components/ui/input'
import { useToast } from '@/components/ui/toast'
import { activateCampaignAction, createCampaignAction } from '../actions'
export function CampaignDialog({ templates }: { templates: { id: string; name: string; audience: string; target: string }[] }) { const toast = useToast(); const [open, setOpen] = React.useState(false); const [name, setName] = React.useState(''); const [templateId, setTemplateId] = React.useState(templates[0]?.id ?? ''); const [frequency, setFrequency] = React.useState('FORTNIGHTLY'); const [pending, startTransition] = React.useTransition(); const submit = () => startTransition(async () => { const r = await createCampaignAction({ name, templateId, frequency, isAnonymousToTarget: true, minimumResponses: 5 }); if (!r.ok) return toast.push({ tone: 'error', title: 'Could not save campaign', description: r.message }); toast.push({ tone: 'success', title: 'Campaign created', description: r.message }); setOpen(false); setName('') }); return <><Button size="sm" onClick={() => setOpen(true)} disabled={!templates.length}>New campaign</Button><Dialog open={open} onClose={() => setOpen(false)} title="Create campaign" description="Save a campaign, review its audience, then activate it when you are ready." footer={<><Button onClick={submit} loading={pending} disabled={!name || !templateId}>Save draft</Button><Button variant="ghost" onClick={() => setOpen(false)}>Cancel</Button></>}><div className="grid gap-3"><Field label="Campaign name" required htmlFor="campaign-name"><Input id="campaign-name" value={name} onChange={(e) => setName(e.target.value)} placeholder="August fortnightly feedback" /></Field><Field label="Template" required htmlFor="campaign-template"><Select id="campaign-template" value={templateId} onChange={(e) => setTemplateId(e.target.value)}>{templates.map((t) => <option key={t.id} value={t.id}>{t.name} — {t.audience.toLowerCase()} to {t.target.toLowerCase()}</option>)}</Select></Field><Field label="Frequency" htmlFor="campaign-frequency"><Select id="campaign-frequency" value={frequency} onChange={(e) => setFrequency(e.target.value)}>{['ONE_TIME','WEEKLY','FORTNIGHTLY','MONTHLY','TERM_WISE','CUSTOM'].map((value) => <option key={value} value={value}>{value.replace('_', ' ').toLowerCase()}</option>)}</Select></Field></div></Dialog></> }
export function ActivateCampaign({ id }: { id: string }) { const toast = useToast(); const [pending, startTransition] = React.useTransition(); return <Button size="sm" onClick={() => startTransition(async () => { const r = await activateCampaignAction(id); toast.push({ tone: r.ok ? 'success' : 'error', title: r.ok ? 'Campaign activated' : 'Could not activate', description: r.message }) })} loading={pending}>Activate</Button> }
