'use client'

import * as React from 'react'
import { CheckCircle2, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/input'
import { useToast } from '@/components/ui/toast'
import { submitFeedbackAction } from './actions'

type Question = { id: string; label: string; description: string | null; type: string; required: boolean; isConcern: boolean; choices: unknown }
type Assignment = { id: string; template: { isAnonymousToTarget: boolean; questions: Question[] }; targetStaff: { firstName: string; lastName: string } | null; subject: { name: string } | null }
export function FeedbackForm({ assignment }: { assignment: Assignment }) {
  const toast = useToast(); const [values, setValues] = React.useState<Record<string, string>>({}); const [concernDetail, setConcernDetail] = React.useState(''); const [pending, startTransition] = React.useTransition(); const [done, setDone] = React.useState(false)
  const set = (id: string, value: string) => setValues((current) => ({ ...current, [id]: value }))
  const hasConcern = assignment.template.questions.some((q) => q.isConcern && values[q.id] === 'CONCERN')
  const submit = () => startTransition(async () => { const answers = assignment.template.questions.filter((q) => values[q.id]).map((q) => ({ questionId: q.id, ...(q.type.startsWith('RATING') ? { rating: Number(values[q.id]) } : { value: values[q.id] }) })); const result = await submitFeedbackAction(assignment.id, { answers, concernDetail: hasConcern ? concernDetail : undefined }); if (!result.ok) { toast.push({ tone: 'error', title: 'Could not submit', description: result.message }); return }; setDone(true); toast.push({ tone: 'success', title: 'Feedback submitted', description: result.message }) })
  if (done) return <div className="rounded-[var(--radius)] border border-line bg-surface p-6 text-center"><CheckCircle2 className="mx-auto size-8 text-success" /><h2 className="mt-3 text-lg font-semibold text-ink">Thank you for sharing.</h2><p className="mt-1 text-sm text-ink-muted">{assignment.template.isAnonymousToTarget ? 'Your individual responses will not be shown to the teacher.' : 'Your feedback has been shared with the school.'}</p></div>
  return <section className="space-y-5"><header><p className="text-sm font-medium text-brand">Help us improve your learning experience</p><h1 className="mt-1 text-2xl font-semibold text-ink">{assignment.targetStaff ? `${assignment.targetStaff.firstName} ${assignment.targetStaff.lastName}` : 'Feedback'}</h1><p className="mt-1 text-sm text-ink-muted">{assignment.subject?.name ?? 'Your class'} · This takes about two minutes.</p>{assignment.template.isAnonymousToTarget ? <p className="mt-3 flex items-center gap-2 text-xs text-ink-muted"><ShieldCheck className="size-4 text-success" /> Your teacher sees aggregate results, not your identity.</p> : null}</header><div className="space-y-5">{assignment.template.questions.map((question, index) => <div key={question.id} className="border-b border-line pb-5 last:border-0"><p className="text-sm font-medium text-ink">{index + 1}. {question.label}{question.required ? <span className="text-danger"> *</span> : null}</p>{question.description ? <p className="mt-1 text-xs text-ink-muted">{question.description}</p> : null}{question.type.startsWith('RATING') ? <div className="mt-3 flex flex-wrap gap-2">{Array.from({ length: question.type === 'RATING_10' ? 10 : 5 }, (_, i) => String(i + 1)).map((rating) => <button key={rating} type="button" onClick={() => set(question.id, rating)} className={`grid size-9 place-items-center rounded-[var(--radius-sm)] border text-sm font-medium transition-colors ${values[question.id] === rating ? 'border-brand bg-brand text-white' : 'border-line-strong text-ink hover:border-brand'}`}>{rating}</button>)}</div> : question.isConcern ? <div className="mt-3 flex gap-2"><Button type="button" variant={values[question.id] === 'NO' ? 'primary' : 'secondary'} size="sm" onClick={() => set(question.id, 'NO')}>No</Button><Button type="button" variant={values[question.id] === 'CONCERN' ? 'primary' : 'secondary'} size="sm" onClick={() => set(question.id, 'CONCERN')}>I want to share privately</Button></div> : <Textarea className="mt-3" value={values[question.id] ?? ''} onChange={(event) => set(question.id, event.target.value)} rows={question.type === 'LONG_TEXT' ? 4 : 2} />}</div>)}</div>{hasConcern ? <div className="rounded-[var(--radius)] bg-[var(--warning-bg)] p-4"><p className="text-sm font-medium text-ink">Share your concern privately</p><p className="mt-1 text-xs text-ink-muted">This is visible only to designated safeguarding staff, never your teacher.</p><Textarea className="mt-3" value={concernDetail} onChange={(event) => setConcernDetail(event.target.value)} rows={4} /></div> : null}<div className="flex justify-end"><Button onClick={submit} loading={pending}>Submit feedback</Button></div></section>
}
