/**
 * Every Prisma model carrying a `tenantId` column. Generated by inspecting the
 * schema; the unit test `tests/tenant-models.test.ts` fails if the schema and
 * this list drift apart, so a new tenant-scoped model cannot be added without
 * also being isolated.
 */
export const TENANT_SCOPED_MODELS = [
  'School',
  'Branding',
  'Setting',
  'Student',
  'Enrollment',
  'Parent',
  'StudentGuardian',
  'Staff',
  'DisciplineRecord',
  'AcademicSession',
  'ClassLevel',
  'Section',
  'Subject',
  'ClassSubject',
  'StudentAttendance',
  'StaffAttendance',
  'LeaveType',
  'LeaveRequest',
  'FeeHead',
  'FeeStructure',
  'FeeStructureItem',
  'FeeConcession',
  'FeeInvoice',
  'FeeInvoiceLine',
  'FeePayment',
  'FeePaymentAllocation',
  'FeeReceipt',
  'FeeRefund',
  'FeePenaltyRule',
  'GradingScale',
  'GradeBand',
  'Exam',
  'ExamClass',
  'ExamSubject',
  'Mark',
  'Result',
  'ReportCardTemplate',
  'CertificateTemplate',
  'Certificate',
  'Homework',
  'HomeworkSubmission',
  'Classwork',
  'TimetablePeriod',
  'TimetableSlot',
  'CalendarEvent',
  'Notice',
  'NoticeTarget',
  'Conversation',
  'ConversationParticipant',
  'Message',
  'Notification',
  'NotificationDelivery',
  'BookCategory',
  'Book',
  'BookCopy',
  'LibraryLoan',
  'AssetCategory',
  'Asset',
  'AssetHistory',
  'Visitor',
  'Appointment',
  'AdmissionLead',
  'LeadFollowUp',
  'LeadActivity',
  'Bus',
  'BusMaintenance',
  'Route',
  'BusStop',
  'TransportAssignment',
  'BusTrip',
  'BusLocation',
  'TransportBoardingLog',
  'Sport',
  'SportsTeam',
  'SportsTeamMember',
  'SchoolEvent',
  'EventParticipant',
  'CmsPage',
  'CmsBlock',
  'CmsPost',
  'CmsMedia',
  'Document',
  'Attachment',
  'ImportBatch',
] as const

export type TenantScopedModel = (typeof TENANT_SCOPED_MODELS)[number]

const set = new Set<string>(TENANT_SCOPED_MODELS)

export function isTenantScoped(model: string | undefined): boolean {
  return !!model && set.has(model)
}

/**
 * Models that carry an optional tenantId (platform rows may have none) and are
 * therefore filtered but not force-created with a tenant.
 */
export const TENANT_OPTIONAL_MODELS = new Set<string>([
  'User',
  'Role',
  'Session',
  'LoginEvent',
  'AuditLog',
  'NotificationTemplate',
  'Job',
  'PaymentEvent',
])

/**
 * SaaS control-plane models. They carry a tenantId but are deliberately NOT
 * scoped by `tenantDb()`: they are owned by the platform, written during
 * provisioning and billing, and read by the super-admin console, which is the
 * one context that is meant to see across tenants. Tenant-facing code reaches
 * them only through `getEntitlements()` and friends, which take an explicit
 * tenantId.
 */
export const PLATFORM_MODELS = new Set<string>([
  'TenantDomain',
  'Subscription',
  'SubscriptionInvoice',
  'TenantEntitlementOverride',
  'UsageMetric',
  'SupportTicket',
])

