/**
 * Every Prisma model carrying a `tenantId` column. Generated by inspecting the
 * schema; the unit test `tests/tenant-models.test.ts` fails if the schema and
 * this list drift apart, so a new tenant-scoped model cannot be added without
 * also being isolated.
 */
export const TENANT_SCOPED_MODELS = [
  'School',
  'Branding',
  'Setting',
  'Student',
  'Enrollment',
  'Parent',
  'StudentGuardian',
  'Staff',
  'DisciplineRecord',
  'AcademicSession',
  'ClassLevel',
  'Section',
  'Subject',
  'ClassSubject',
  'Curriculum',
  'Chapter',
  'Topic',
  'LearningOutcome',
  'Question',
  'QuestionOption',
  'QuestionTopic',
  'AssessmentType',
  'PaperTemplate',
  'Assessment',
  'AssessmentSection',
  'AssessmentQuestion',
  'QuestionUsage',
  'AssessmentAssignment',
  'AssessmentAttempt',
  'StudentAnswer',
  'StudentAttendance',
  'StaffAttendance',
  'StaffSalaryStructure',
  'StaffPayslip',
  'StaffAppraisal',
  'StaffAppraisalRating',
  'ScoreWeight',
  'ScoreSnapshot',
  'RoiCalculation',
  'GpsIngestToken',
  'LeaveType',
  'LeaveRequest',
  'FeeHead',
  'FeeStructure',
  'FeeStructureItem',
  'StudentFeeOption',
  'FeeConcession',
  'FeedbackTemplate',
  'FeedbackQuestion',
  'FeedbackCampaign',
  'FeedbackAssignment',
  'FeedbackResponse',
  'FeedbackAnswer',
  'FeedbackConcern',
  'FeedbackModeration',
  'FeedbackActionItem',
  'TeacherStudentFeedback',
  'FeeInvoice',
  'FeeInvoiceLine',
  'FeePayment',
  'FeePaymentAllocation',
  'FeeReceipt',
  'FeeRefund',
  'FeePenaltyRule',
  'SchoolExpense',
  'GradingScale',
  'GradeBand',
  'Exam',
  'ExamClass',
  'ExamSubject',
  'Mark',
  'Result',
  'AdmitCard',
  'ReportCardTemplate',
  'CertificateTemplate',
  'Certificate',
  'Homework',
  'HomeworkSubmission',
  'Classwork',
  'TimetablePeriod',
  'TimetableSlot',
  'CalendarEvent',
  'Notice',
  'NoticeTarget',
  'Conversation',
  'ConversationParticipant',
  'Message',
  'Notification',
  'NotificationDelivery',
  'BookCategory',
  'Book',
  'BookCopy',
  'LibraryLoan',
  'AssetCategory',
  'Asset',
  'AssetHistory',
  'Visitor',
  'Appointment',
  'AdmissionLead',
  'LeadFollowUp',
  'LeadActivity',
  'Bus',
  'BusMaintenance',
  'Route',
  'BusStop',
  'TransportAssignment',
  'BusTrip',
  'BusLocation',
  'TransportBoardingLog',
  'Sport',
  'SportsTeam',
  'SportsTeamMember',
  'SchoolEvent',
  'EventParticipant',
  'CmsPage',
  'CmsBlock',
  'CmsPost',
  'CmsMedia',
  'Document',
  'Attachment',
  'ImportBatch',
  'SupportTicket',
  'PushSubscription',
  'TenantDomain',

  // Teacher Knowledge Refresh & Readiness
  'TeacherRefreshConfig',
  'TeacherKnowledgeProfile',
  'TeacherRefreshAssessment',
  'TeacherRefreshQuestion',
  'TeacherRefreshAttempt',
  'TeacherRefreshAttemptAnswer',
] as const

export type TenantScopedModel = (typeof TENANT_SCOPED_MODELS)[number]

const set = new Set<string>(TENANT_SCOPED_MODELS)

export function isTenantScoped(model: string | undefined): boolean {
  return !!model && set.has(model)
}

/**
 * Models that carry an OPTIONAL tenantId, because a platform-owned row may
 * legitimately have none.
 *
 * They are filtered on read but never stamped on create: a caller that makes
 * one of these has to say which tenant it belongs to, and some of them are
 * deliberately created with no tenant at all.
 *
 * They split by what a tenant is allowed to see.
 */

/**
 * Strictly the tenant's own rows. A platform row here is not "shared", it is
 * simply none of a school's business — nobody at one school may read another
 * school's users, sessions, audit trail or queued jobs, and nor may they read
 * the platform's.
 */
export const TENANT_OWNED_OPTIONAL_MODELS = new Set<string>([
  'User',
  'Session',
  'LoginEvent',
  'AuditLog',
  'Job',
  'PaymentEvent',
])

/**
 * The tenant's own rows plus the platform's defaults. System roles and stock
 * notification templates are created with a null tenantId and every school
 * reads them; a school may also define its own alongside.
 */
export const TENANT_SHARED_OPTIONAL_MODELS = new Set<string>([
  'Role',
  'NotificationTemplate',
])

/** Every model with an optional tenantId, whichever way it is filtered. */
export const TENANT_OPTIONAL_MODELS = new Set<string>([
  ...TENANT_OWNED_OPTIONAL_MODELS,
  ...TENANT_SHARED_OPTIONAL_MODELS,
])

export function isTenantOwnedOptional(model: string | undefined): boolean {
  return !!model && TENANT_OWNED_OPTIONAL_MODELS.has(model)
}

export function isTenantSharedOptional(model: string | undefined): boolean {
  return !!model && TENANT_SHARED_OPTIONAL_MODELS.has(model)
}

/**
 * SaaS control-plane models. They carry a tenantId but are deliberately NOT
 * scoped by `tenantDb()`: they are owned by the platform, written during
 * provisioning and billing, and read by the super-admin console, which is the
 * one context that is meant to see across tenants. Tenant-facing code reaches
 * them only through `getEntitlements()` and friends, which take an explicit
 * tenantId.
 *
 * `TenantDomain` is tenant-scoped (schools manage their own hosts); host
 * resolution uses the unscoped `prisma` client by unique `host`.
 */
export const PLATFORM_MODELS = new Set<string>([
  'Subscription',
  'SubscriptionInvoice',
  'TenantEntitlementOverride',
  'UsageMetric',
])

/**
 * Platform-console models with no tenantId. tenantDb() must refuse them so a
 * school request cannot list Growth CRM prospects through the unscoped path
 * that non-tenant models currently take.
 */
export const PLATFORM_ONLY_MODELS = new Set<string>([
  'CrmSchool',
  'CrmContact',
  'CrmOpportunity',
  'CrmActivity',
  'CrmFollowUp',
  'CrmVisit',
  'CrmMeeting',
  'CrmTask',
  'CrmReminderSend',
  'CrmTemplate',
  'CrmCommunication',
  'CrmDiscoveryLocation',
  'CrmDiscoverySettings',
  'CrmDiscoveryRun',
  'CrmDiscoveryCandidate',
  'CrmDiscoveryEvidence',
])

export function isPlatformOnly(model: string | undefined): boolean {
  return !!model && PLATFORM_ONLY_MODELS.has(model)
}

